/** Static city lists keyed by ISO 3166-1 alpha-2 country code. */
export const citiesByCountry: Record<string, string[]> = {
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "Las Vegas",
    "Miami",
    "Atlanta",
    "Orlando",
    "New Orleans",
    "Honolulu",
    "Portland",
    "Nashville",
    "Charleston",
    "Savannah",
    "Santa Fe",
    "Aspen",
    "Anchorage",
    "Salt Lake City",
    "Minneapolis",
    "Detroit",
    "Tampa",
    "San Juan",
    "Key West",
    "Sedona",
    "Napa",
    "Maui",
    "Kauai",
  ],
  CA: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Halifax",
    "Victoria",
    "Whistler",
    "Banff",
    "Jasper",
    "Niagara Falls",
    "Kelowna",
    "Churchill",
    "St. John's",
    "Charlottetown",
    "Moncton",
    "Saskatoon",
    "Regina",
    "London",
    "Hamilton",
    "Kitchener",
    "Mississauga",
    "Kingston",
    "Tofino",
    "Yellowknife",
    "Whitehorse",
    "Iqaluit",
    "Trois-Rivières",
    "Gatineau",
    "Laval",
    "Brampton",
    "Surrey",
    "Burnaby",
    "Richmond",
    "Windsor",
    "Thunder Bay",
  ],
  GB: [
    "London",
    "Edinburgh",
    "Manchester",
    "Birmingham",
    "Glasgow",
    "Liverpool",
    "Bristol",
    "Leeds",
    "Sheffield",
    "Newcastle",
    "Cardiff",
    "Belfast",
    "Oxford",
    "Cambridge",
    "Brighton",
    "Bath",
    "York",
    "Canterbury",
    "Stratford-upon-Avon",
    "Inverness",
    "Aberdeen",
    "St Andrews",
    "Liverpool",
    "Nottingham",
    "Leicester",
    "Southampton",
    "Portsmouth",
    "Plymouth",
    "Exeter",
    "Cornwall",
    "Lake District",
    "Snowdonia",
    "Isle of Skye",
    "Isle of Wight",
    "Jersey",
    "Guernsey",
    "Durham",
    "Chester",
    "Windsor",
    "Winchester",
  ],
  FR: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Cannes",
    "Monaco",
    "Avignon",
    "Aix-en-Provence",
    "Annecy",
    "Chamonix",
    "Biarritz",
    "Saint-Tropez",
    "Colmar",
    "Dijon",
    "Tours",
    "Loire Valley",
    "Normandy",
    "Brittany",
    "Provence",
    "Corsica",
    "Lourdes",
    "Versailles",
    "Fontainebleau",
    "Grenoble",
    "Toulon",
    "Perpignan",
    "Carcassonne",
    "Bayonne",
    "La Rochelle",
    "Rouen",
    "Metz",
    "Nancy",
  ],
  DE: [
    "Berlin",
    "Munich",
    "Hamburg",
    "Frankfurt",
    "Cologne",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Dresden",
    "Hannover",
    "Nuremberg",
    "Bremen",
    "Heidelberg",
    "Freiburg",
    "Rothenburg ob der Tauber",
    "Black Forest",
    "Rhine Valley",
    "Bamberg",
    "Regensburg",
    "Passau",
    "Lübeck",
    "Rostock",
    "Potsdam",
    "Weimar",
    "Erfurt",
    "Würzburg",
    "Trier",
    "Aachen",
    "Bonn",
    "Mainz",
    "Koblenz",
    "Garmisch-Partenkirchen",
    "Berchtesgaden",
    "Rügen",
    "Sylt",
    "Baden-Baden",
    "Füssen",
    "Cologne Cathedral",
  ],
  IT: [
    "Rome",
    "Milan",
    "Venice",
    "Florence",
    "Naples",
    "Turin",
    "Bologna",
    "Genoa",
    "Palermo",
    "Verona",
    "Pisa",
    "Siena",
    "Amalfi Coast",
    "Capri",
    "Positano",
    "Cinque Terre",
    "Lake Como",
    "Lake Garda",
    "Sorrento",
    "Pompeii",
    "Sicily",
    "Taormina",
    "Catania",
    "Sardinia",
    "Cagliari",
    "Lucca",
    "Perugia",
    "Assisi",
    "Ravenna",
    "Trieste",
    "Bari",
    "Matera",
    "Alberobello",
    "Portofino",
    "Cortona",
    "San Gimignano",
    "Montepulciano",
    "Bolzano",
    "Trento",
    "Padua",
  ],
  ES: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Bilbao",
    "Malaga",
    "Granada",
    "Toledo",
    "Salamanca",
    "Córdoba",
    "San Sebastián",
    "Ibiza",
    "Mallorca",
    "Menorca",
    "Tenerife",
    "Gran Canaria",
    "Lanzarote",
    "Santiago de Compostela",
    "Pamplona",
    "Zaragoza",
    "Alicante",
    "Murcia",
    "Cádiz",
    "Ronda",
    "Marbella",
    "Costa del Sol",
    "Costa Brava",
    "Sitges",
    "Girona",
    "Segovia",
    "Ávila",
    "Cuenca",
    "Burgos",
    "León",
    "Oviedo",
    "Santander",
    "La Rioja",
    "Jerez de la Frontera",
    "Tarifa",
    "Formentera",
  ],
  JP: [
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Hiroshima",
    "Sendai",
    "Nara",
    "Kanazawa",
    "Hakone",
    "Nikko",
    "Kamakura",
    "Takayama",
    "Shirakawa-go",
    "Miyajima",
    "Hokkaido",
    "Okinawa",
    "Naha",
    "Ishigaki",
    "Nagasaki",
    "Kumamoto",
    "Beppu",
    "Kagoshima",
    "Matsumoto",
    "Nagano",
    "Hakuba",
    "Niseko",
    "Furano",
    "Asahikawa",
    "Aomori",
    "Akita",
    "Miyazaki",
    "Matsuyama",
    "Takamatsu",
    "Naoshima",
    "Koya-san",
    "Ise",
  ],
  PH: [
    "Manila",
    "Cebu City",
    "Davao",
    "Quezon City",
    "Makati",
    "Tagaytay",
    "Baguio",
    "Boracay",
    "Palawan",
    "El Nido",
    "Coron",
    "Puerto Princesa",
    "Siargao",
    "Bohol",
    "Panglao",
    "Vigan",
    "Batanes",
    "Sagada",
    "Banaue",
    "Legazpi",
    "Camiguin",
    "Dumaguete",
    "Siquijor",
    "Iloilo",
    "Bacolod",
    "Cagayan de Oro",
    "Zamboanga",
    "General Santos",
    "Angeles City",
    "Subic",
    "La Union",
    "Baler",
    "Sorsogon",
    "Tacloban",
    "Kalibo",
    "Malapascua",
    "Moalboal",
    "Oslob",
    "Samar",
    "Mindoro",
  ],
  AU: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Cairns",
    "Darwin",
    "Hobart",
    "Great Barrier Reef",
    "Uluru",
    "Whitsundays",
    "Byron Bay",
    "Noosa",
    "Port Douglas",
    "Broome",
    "Alice Springs",
    "Kakadu",
    "Blue Mountains",
    "Hunter Valley",
    "Barossa Valley",
    "Margaret River",
    "Rottnest Island",
    "Kangaroo Island",
    "Fraser Island",
    "Hamilton Island",
    "Tasmania",
    "Launceston",
    "Newcastle",
    "Wollongong",
    "Sunshine Coast",
    "Townsville",
    "Mackay",
    "Rockhampton",
    "Ballarat",
    "Bendigo",
    "Geelong",
    "Phillip Island",
    "Great Ocean Road",
  ],
  AE: [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain",
    "Al Ain",
    "Jebel Ali",
    "Palm Jumeirah",
    "Dubai Marina",
    "Jumeirah",
    "Deira",
    "Bur Dubai",
    "Yas Island",
    "Saadiyat Island",
    "Al Maktoum",
    "Hatta",
    "Liwa Oasis",
    "Khor Fakkan",
    "Kalba",
    "Dibba",
    "Masafi",
    "Madinat Jumeirah",
    "Business Bay",
    "Downtown Dubai",
    "Dubai Creek",
    "Al Barsha",
    "JBR",
    "Dubai Hills",
    "Mirdif",
    "Silicon Oasis",
    "Dubai South",
    "Expo City",
    "Global Village",
    "Miracle Garden",
    "Desert Safari",
    "Al Qudra",
    "Bluewaters Island",
  ],
  SG: [
    "Singapore",
    "Sentosa",
    "Marina Bay",
    "Orchard Road",
    "Chinatown",
    "Little India",
    "Kampong Glam",
    "Clarke Quay",
    "Bugis",
    "Jurong",
    "Tampines",
    "Woodlands",
    "Changi",
    "Punggol",
    "Sengkang",
    "Ang Mo Kio",
    "Toa Payoh",
    "Bishan",
    "Serangoon",
    "Hougang",
    "Bedok",
    "Pasir Ris",
    "Clementi",
    "Queenstown",
    "Bukit Timah",
    "Holland Village",
    "East Coast",
    "Gardens by the Bay",
    "Marina South",
    "Pulau Ubin",
    "Pulau Hantu",
    "Kusu Island",
    "St. John's Island",
    "Lazarus Island",
    "MacRitchie",
    "Bukit Batok",
    "Jurong Lake",
    "Haw Par Villa",
    "Raffles Place",
    "Tanjong Pagar",
  ],
  KR: [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Ulsan",
    "Suwon",
    "Jeju City",
    "Seogwipo",
    "Gyeongju",
    "Andong",
    "Jeonju",
    "Sokcho",
    "Gangneung",
    "Pyeongchang",
    "Chuncheon",
    "Yeosu",
    "Tongyeong",
    "Geoje",
    "Pohang",
    "Changwon",
    "Jinhae",
    "Gyeongju",
    "Haeundae",
    "Myeongdong",
    "Hongdae",
    "Itaewon",
    "Insadong",
    "Bukchon",
    "Nami Island",
    "Everland",
    "Lotte World",
    "DMZ",
    "Panmunjom",
    "Boryeong",
    "Mokpo",
    "Gunsan",
    "Gunsan",
    "Muan",
  ],
  TH: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Krabi",
    "Koh Samui",
    "Koh Phangan",
    "Koh Tao",
    "Hua Hin",
    "Cha-am",
    "Ayutthaya",
    "Sukhothai",
    "Chiang Rai",
    "Pai",
    "Mae Hong Son",
    "Kanchanaburi",
    "Erawan",
    "Koh Lanta",
    "Koh Phi Phi",
    "Railay",
    "Ao Nang",
    "Koh Chang",
    "Koh Kood",
    "Trat",
    "Hat Yai",
    "Songkhla",
    "Surat Thani",
    "Nakhon Ratchasima",
    "Udon Thani",
    "Khon Kaen",
    "Lampang",
    "Lamphun",
    "Nan",
    "Mae Sai",
    "Golden Triangle",
    "Khao Yai",
    "Khao Sok",
    "Similan Islands",
    "Phang Nga",
    "Koh Yao",
  ],
  IN: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Agra",
    "Varanasi",
    "Goa",
    "Panaji",
    "Kochi",
    "Munnar",
    "Alleppey",
    "Kerala Backwaters",
    "Rishikesh",
    "Haridwar",
    "Manali",
    "Shimla",
    "Dharamshala",
    "Leh",
    "Ladakh",
    "Srinagar",
    "Amritsar",
    "Chandigarh",
    "Pushkar",
    "Jaisalmer",
    "Hampi",
    "Mysore",
    "Ooty",
    "Darjeeling",
    "Gangtok",
    "Andaman Islands",
    "Port Blair",
    "Lakshadweep",
    "Khajuraho",
  ],
  NL: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Maastricht",
    "Haarlem",
    "Leiden",
    "Delft",
    "Dordrecht",
    "Nijmegen",
    "Arnhem",
    "Tilburg",
    "Breda",
    "Enschede",
    "Zwolle",
    "Amersfoort",
    "Apeldoorn",
    "Den Bosch",
    "Volendam",
    "Zaanse Schans",
    "Keukenhof",
    "Giethoorn",
    "Kinderdijk",
    "Texel",
    "Vlieland",
    "Terschelling",
    "Ameland",
    "Scheveningen",
    "Zandvoort",
    "Noordwijk",
    "Marken",
    "Edam",
    "Alkmaar",
    "Hoorn",
    "Enkhuizen",
    "Middelburg",
    "Vlissingen",
    "Bergen op Zoom",
  ],
  CH: [
    "Zurich",
    "Geneva",
    "Basel",
    "Bern",
    "Lausanne",
    "Lucerne",
    "Interlaken",
    "Zermatt",
    "St. Moritz",
    "Davos",
    "Grindelwald",
    "Lauterbrunnen",
    "Jungfraujoch",
    "Montreux",
    "Vevey",
    "Lugano",
    "Locarno",
    "Ascona",
    "Bellinzona",
    "Chur",
    "Arosa",
    "Engelberg",
    "Gstaad",
    "Verbier",
    "Crans-Montana",
    "Saas-Fee",
    "Andermatt",
    "Lauterbrunnen",
    "Wengen",
    "Mürren",
    "Thun",
    "Spiez",
    "Neuchâtel",
    "Fribourg",
    "Sion",
    "Martigny",
    "St. Gallen",
    "Winterthur",
    "Baden",
    "Schaffhausen",
  ],
  SE: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
    "Lund",
    "Umeå",
    "Gävle",
    "Kiruna",
    "Abisko",
    "Luleå",
    "Visby",
    "Gotland",
    "Kalmar",
    "Karlskrona",
    "Ystad",
    "Malmö",
    "Helsingborg",
    "Lund",
    "Trollhättan",
    "Borås",
    "Karlstad",
    "Sundsvall",
    "Östersund",
    "Åre",
    "Sälen",
    "Falun",
    "Mora",
    "Sigtuna",
    "Mariefred",
    "Gripsholm",
    "Drottningholm",
    "Skansen",
    "Södermalm",
    "Gamla Stan",
  ],
  NO: [
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Tromsø",
    "Ålesund",
    "Kristiansand",
    "Drammen",
    "Fredrikstad",
    "Sandnes",
    "Bodø",
    "Lofoten",
    "Svolvær",
    "Reine",
    "Geiranger",
    "Flåm",
    "Gudvangen",
    "Stavanger",
    "Preikestolen",
    "Kjerag",
    "Trolltunga",
    "Odda",
    "Røros",
    "Lillehammer",
    "Geilo",
    "Hemsedal",
    "Trysil",
    "Alta",
    "Kirkenes",
    "North Cape",
    "Svalbard",
    "Longyearbyen",
    "Hammerfest",
    "Harstad",
    "Narvik",
    "Mo i Rana",
    "Molde",
    "Kristiansund",
    "Sandefjord",
    "Skien",
  ],
  DK: [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Helsingør",
    "Skagen",
    "Rønne",
    "Bornholm",
    "Billund",
    "Legoland",
    "Fredericia",
    "Silkeborg",
    "Viborg",
    "Herning",
    "Hillerød",
    "Frederiksborg",
    "Dragør",
    "Møn",
    "Ribe",
    "Ebeltoft",
    "Aarhus",
    "Grenaa",
    "Fanø",
    "Rømø",
    "Thy",
    "Hanstholm",
    "Løkken",
    "Blokhus",
    "Hirtshals",
    "Frederikshavn",
    "Sønderborg",
    "Tønder",
    "Middelfart",
    "Næstved",
  ],
  FI: [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Lahti",
    "Kuopio",
    "Pori",
    "Rovaniemi",
    "Levi",
    "Ylläs",
    "Saariselkä",
    "Inari",
    "Ivalo",
    "Kemi",
    "Kotka",
    "Joensuu",
    "Lappeenranta",
    "Savonlinna",
    "Porvoo",
    "Naantali",
    "Turku Archipelago",
    "Åland",
    "Mariehamn",
    "Tampere",
    "Hämeenlinna",
    "Jyväskylä",
    "Kuopio",
    "Savonlinna",
    "Mikkeli",
    "Imatra",
    "Koli",
    "Lakeland",
    "Saimaa",
    "Nuuksio",
    "Seurasaari",
    "Suomenlinna",
    "Lapland",
  ],
  PT: [
    "Lisbon",
    "Porto",
    "Faro",
    "Coimbra",
    "Braga",
    "Évora",
    "Sintra",
    "Cascais",
    "Óbidos",
    "Nazaré",
    "Aveiro",
    "Guimarães",
    "Viana do Castelo",
    "Bragança",
    "Viseu",
    "Castelo Branco",
    "Guarda",
    "Portalegre",
    "Beja",
    "Setúbal",
    "Almada",
    "Funchal",
    "Madeira",
    "Ponta Delgada",
    "Azores",
    "Lagos",
    "Albufeira",
    "Portimão",
    "Tavira",
    "Sagres",
    "Évora",
    "Monsaraz",
    "Marvão",
    "Tomar",
    "Batalha",
    "Alcobaça",
    "Fatima",
    "Douro Valley",
    "Pinhão",
    "Peso da Régua",
  ],
  GR: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Chania",
    "Rhodes",
    "Corfu",
    "Santorini",
    "Mykonos",
    "Paros",
    "Naxos",
    "Milos",
    "Crete",
    "Rethymno",
    "Agios Nikolaos",
    "Zakynthos",
    "Kefalonia",
    "Lefkada",
    "Skiathos",
    "Skopelos",
    "Hydra",
    "Spetses",
    "Poros",
    "Aegina",
    "Delphi",
    "Meteora",
    "Kalambaka",
    "Olympia",
    "Mycenae",
    "Nafplio",
    "Monemvasia",
    "Chalkidiki",
    "Thessaloniki",
    "Kavala",
    "Thassos",
    "Samothrace",
    "Lesvos",
    "Chios",
    "Kos",
    "Patmos",
  ],
  MX: [
    "Mexico City",
    "Cancún",
    "Playa del Carmen",
    "Tulum",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Oaxaca",
    "Mérida",
    "Cozumel",
    "Los Cabos",
    "Puerto Vallarta",
    "Mazatlán",
    "Acapulco",
    "Taxco",
    "San Miguel de Allende",
    "Guanajuato",
    "Querétaro",
    "Morelia",
    "Patzcuaro",
    "Chiapas",
    "San Cristóbal de las Casas",
    "Palenque",
    "Campeche",
    "Veracruz",
    "Xalapa",
    "Cuernavaca",
    "Teotihuacán",
    "Chichen Itza",
    "Uxmal",
    "Isla Mujeres",
    "Holbox",
    "Bacalar",
    "Huatulco",
    "Zihuatanejo",
    "Ixtapa",
    "Manzanillo",
    "Loreto",
    "La Paz",
    "Copper Canyon",
  ],
  BR: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Belém",
    "Goiânia",
    "Florianópolis",
    "Natal",
    "João Pessoa",
    "Maceió",
    "Aracaju",
    "Vitória",
    "Campo Grande",
    "Cuiabá",
    "Porto Velho",
    "Rio Branco",
    "Macapá",
    "Boa Vista",
    "Palmas",
    "Fernando de Noronha",
    "Ilha Grande",
    "Paraty",
    "Búzios",
    "Angra dos Reis",
    "Gramado",
    "Canela",
    "Bonito",
    "Chapada Diamantina",
    "Lençóis Maranhenses",
    "Jericoacoara",
    "Olinda",
    "Ouro Preto",
    "Tiradentes",
    "Foz do Iguaçu",
  ],
  AR: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "Bariloche",
    "Ushuaia",
    "El Calafate",
    "Salta",
    "Jujuy",
    "Iguazú",
    "Mar del Plata",
    "La Plata",
    "Tucumán",
    "San Juan",
    "San Luis",
    "Neuquén",
    "Comodoro Rivadavia",
    "Trelew",
    "Puerto Madryn",
    "Península Valdés",
    "El Chaltén",
    "Perito Moreno",
    "Cafayate",
    "Tilcara",
    "Humahuaca",
    "Purmamarca",
    "Villa La Angostura",
    "San Martín de los Andes",
    "Esquel",
    "Trevelin",
    "Villa General Belgrano",
    "Carlos Paz",
    "Alta Gracia",
    "Merlo",
    "Villa Carlos Paz",
    "Pinamar",
    "Cariló",
    "Necochea",
    "Tandil",
    "Sierra de la Ventana",
  ],
  CL: [
    "Santiago",
    "Valparaíso",
    "Viña del Mar",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Iquique",
    "Arica",
    "Punta Arenas",
    "Puerto Varas",
    "Puerto Montt",
    "Chiloé",
    "Castro",
    "Ancud",
    "Pucón",
    "Villarrica",
    "Temuco",
    "Osorno",
    "Frutillar",
    "San Pedro de Atacama",
    "Calama",
    "San Pedro de Atacama",
    "El Tatio",
    "Valle de la Luna",
    "Easter Island",
    "Hanga Roa",
    "Torres del Paine",
    "Puerto Natales",
    "Coyhaique",
    "Balmaceda",
    "Chaitén",
    "Futaleufú",
    "Cochamó",
    "Valdivia",
    "Niebla",
    "Corral",
    "Talca",
    "Curicó",
    "Rancagua",
    "San Fernando",
  ],
  ZA: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Kimberley",
    "Polokwane",
    "Nelspruit",
    "Stellenbosch",
    "Franschhoek",
    "Paarl",
    "Hermanus",
    "Knysna",
    "Plettenberg Bay",
    "George",
    "Oudtshoorn",
    "Mossel Bay",
    "Swellendam",
    "Wilderness",
    "Sedgefield",
    "Tsitsikamma",
    "Addo",
    "Kruger National Park",
    "Hazyview",
    "Sabie",
    "Graskop",
    "Blyde River Canyon",
    "Pilanesberg",
    "Sun City",
    "Madikwe",
    "Drakensberg",
    "Underberg",
    "Sanibona",
    "Richards Bay",
    "Ballito",
    "Umhlanga",
    "Soweto",
    "Sandton",
  ],
  EG: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Luxor",
    "Aswan",
    "Sharm El Sheikh",
    "Hurghada",
    "Dahab",
    "Marsa Alam",
    "El Gouna",
    "Siwa Oasis",
    "Bahariya Oasis",
    "Fayoum",
    "Minya",
    "Asyut",
    "Sohag",
    "Qena",
    "Edfu",
    "Kom Ombo",
    "Abu Simbel",
    "Port Said",
    "Suez",
    "Ismailia",
    "Damietta",
    "Marsa Matruh",
    "El Alamein",
    "Sinai",
    "Saint Catherine",
    "Taba",
    "Nuweiba",
    "Safaga",
    "Quseir",
    "El Minya",
    "Beni Suef",
    "Zagazig",
    "Mansoura",
    "Tanta",
    "Damanhur",
    "Rosetta",
    "El Arish",
  ],
  CN: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Chongqing",
    "Hangzhou",
    "Xi'an",
    "Nanjing",
    "Wuhan",
    "Suzhou",
    "Tianjin",
    "Qingdao",
    "Dalian",
    "Xiamen",
    "Kunming",
    "Lhasa",
    "Guilin",
    "Yangshuo",
    "Zhangjiajie",
    "Huangshan",
    "Lijiang",
    "Dali",
    "Shangri-La",
    "Harbin",
    "Changchun",
    "Shenyang",
    "Jinan",
    "Zhengzhou",
    "Changsha",
    "Fuzhou",
    "Haikou",
    "Sanya",
    "Urumqi",
    "Kashgar",
    "Dunhuang",
    "Pingyao",
    "Luoyang",
    "Kaifeng",
    "Wuxi",
  ],
  NZ: [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Queenstown",
    "Rotorua",
    "Dunedin",
    "Hamilton",
    "Tauranga",
    "Napier",
    "Hastings",
    "Nelson",
    "Blenheim",
    "Kaikōura",
    "Franz Josef",
    "Fox Glacier",
    "Te Anau",
    "Milford Sound",
    "Wanaka",
    "Arrowtown",
    "Cromwell",
    "Mount Cook",
    "Lake Tekapo",
    "Twizel",
    "Oamaru",
    "Timaru",
    "Invercargill",
    "Stewart Island",
    "Bay of Islands",
    "Paihia",
    "Russell",
    "Kerikeri",
    "Whangārei",
    "Taupō",
    "Tongariro",
    "Whakatāne",
    "Gisborne",
    "New Plymouth",
    "Palmerston North",
    "Whanganui",
    "Martinborough",
  ],
  ID: [
    "Jakarta",
    "Bali",
    "Denpasar",
    "Ubud",
    "Seminyak",
    "Canggu",
    "Surabaya",
    "Bandung",
    "Yogyakarta",
    "Borobudur",
    "Prambanan",
    "Lombok",
    "Gili Islands",
    "Komodo",
    "Labuan Bajo",
    "Flores",
    "Sumba",
    "Raja Ampat",
    "Sorong",
    "Maluku",
    "Banda Islands",
    "Medan",
    "Lake Toba",
    "Padang",
    "Bukittinggi",
    "Palembang",
    "Makassar",
    "Manado",
    "Bunaken",
    "Balikpapan",
    "Banjarmasin",
    "Pontianak",
    "Bogor",
    "Puncak",
    "Anyer",
    "Carita",
    "Belitung",
    "Tanjung Pinang",
    "Batam",
    "Bintan",
  ],
  MY: [
    "Kuala Lumpur",
    "George Town",
    "Penang",
    "Langkawi",
    "Malacca",
    "Johor Bahru",
    "Kota Kinabalu",
    "Kuching",
    "Ipoh",
    "Cameron Highlands",
    "Genting Highlands",
    "Tioman Island",
    "Perhentian Islands",
    "Redang",
    "Pangkor",
    "Pulau Kapas",
    "Taman Negara",
    "Fraser's Hill",
    "Kuala Terengganu",
    "Kota Bharu",
    "Alor Setar",
    "Kuantan",
    "Cherating",
    "Miri",
    "Sibu",
    "Sandakan",
    "Semporna",
    "Mabul",
    "Sipadan",
    "Kundasang",
    "Mount Kinabalu",
    "Putrajaya",
    "Cyberjaya",
    "Shah Alam",
    "Petaling Jaya",
    "Subang Jaya",
    "Seremban",
    "Port Dickson",
    "Melaka",
    "Taiping",
  ],
  VN: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hoi An",
    "Hue",
    "Nha Trang",
    "Da Lat",
    "Phu Quoc",
    "Ha Long Bay",
    "Cat Ba",
    "Sapa",
    "Mai Chau",
    "Ninh Binh",
    "Tam Coc",
    "Phong Nha",
    "Quy Nhon",
    "Mui Ne",
    "Phan Thiet",
    "Vung Tau",
    "Can Tho",
    "Mekong Delta",
    "Ben Tre",
    "My Tho",
    "Chau Doc",
    "Ha Giang",
    "Dong Van",
    "Bac Ha",
    "Cao Bang",
    "Ban Gioc",
    "Con Dao",
    "Phu Yen",
    "Tuy Hoa",
    "Pleiku",
    "Buon Ma Thuot",
    "Dalat",
    "Bao Loc",
    "Vinh",
    "Thanh Hoa",
    "Hai Phong",
    "Ha Long",
  ],
  TR: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Antalya",
    "Bodrum",
    "Marmaris",
    "Fethiye",
    "Ölüdeniz",
    "Cappadocia",
    "Göreme",
    "Pamukkale",
    "Ephesus",
    "Kuşadası",
    "Çeşme",
    "Alaçatı",
    "Bursa",
    "Trabzon",
    "Rize",
    "Kaçkar",
    "Mardin",
    "Şanlıurfa",
    "Gaziantep",
    "Adana",
    "Mersin",
    "Konya",
    "Kayseri",
    "Nevşehir",
    "Safranbolu",
    "Amasra",
    "Amasya",
    "Edirne",
    "Gallipoli",
    "Troy",
    "Assos",
    "Ayvalık",
    "Bergama",
    "Datça",
    "Kaş",
    "Kalkan",
    "Side",
  ],
  PL: [
    "Warsaw",
    "Kraków",
    "Gdańsk",
    "Wrocław",
    "Poznań",
    "Łódź",
    "Katowice",
    "Lublin",
    "Białystok",
    "Szczecin",
    "Toruń",
    "Zakopane",
    "Tatra Mountains",
    "Zakopane",
    "Wieliczka",
    "Auschwitz",
    "Oświęcim",
    "Malbork",
    "Sopot",
    "Gdynia",
    "Hel",
    "Mazury",
    "Mikołajki",
    "Giżycko",
    "Białowieża",
    "Lublin",
    "Kazimierz Dolny",
    "Sandomierz",
    "Zamość",
    "Wrocław",
    "Karpacz",
    "Kłodzko",
    "Kłodzko Valley",
    "Sudetes",
    "Bieszczady",
    "Rzeszów",
    "Przemyśl",
    "Suwałki",
    "Augustów",
    "Hel Peninsula",
  ],
  AT: [
    "Vienna",
    "Salzburg",
    "Innsbruck",
    "Graz",
    "Linz",
    "Klagenfurt",
    "Hallstatt",
    "Zell am See",
    "Kitzbühel",
    "St. Anton",
    "Ischgl",
    "Mayrhofen",
    "Sölden",
    "Obertauern",
    "Bad Gastein",
    "Bad Ischl",
    "Wachau",
    "Melk",
    "Dürnstein",
    "Krems",
    "Bregenz",
    "Dornbirn",
    "Feldkirch",
    "Vorarlberg",
    "Gmunden",
    "Traunsee",
    "Mondsee",
    "Fuschlsee",
    "Wolfgangsee",
    "Semmering",
    "Mariazell",
    "Eisenstadt",
    "Burgenland",
    "Neusiedler See",
    "Styria",
    "Graz",
    "Leoben",
    "Murau",
    "Schladming",
    "Dachstein",
  ],
  BE: [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Bruges",
    "Liège",
    "Charleroi",
    "Namur",
    "Leuven",
    "Mechelen",
    "Ostend",
    "Knokke",
    "Dinant",
    "Spa",
    "Ardennes",
    "Bouillon",
    "Tournai",
    "Mons",
    "Ypres",
    "Ieper",
    "Kortrijk",
    "Hasselt",
    "Genk",
    "Aalst",
    "Dendermonde",
    "Blankenberge",
    "De Haan",
    "De Panne",
    "Nieuwpoort",
    "Veurne",
    "Poperinge",
    "Diksmuide",
    "Diksmuide",
    "Rochefort",
    "La Roche-en-Ardenne",
    "Malmedy",
    "Stavelot",
    "Spa-Francorchamps",
    "Waterloo",
  ],
  IE: [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Waterford",
    "Kilkenny",
    "Killarney",
    "Dingle",
    "Ring of Kerry",
    "Cliffs of Moher",
    "Burren",
    "Connemara",
    "Westport",
    "Achill Island",
    "Sligo",
    "Donegal",
    "Letterkenny",
    "Bundoran",
    "Wicklow",
    "Glendalough",
    "Howth",
    "Malahide",
    "Dún Laoghaire",
    "Bray",
    "Wexford",
    "Kilmore Quay",
    "Hook Head",
    "New Ross",
    "Cashel",
    "Rock of Cashel",
    "Blarney",
    "Kinsale",
    "Cobh",
    "Midleton",
    "Youghal",
    "Tralee",
    "Kenmare",
    "Bantry",
    "Skibbereen",
    "Clifden",
  ],
  CO: [
    "Bogotá",
    "Medellín",
    "Cartagena",
    "Cali",
    "Barranquilla",
    "Santa Marta",
    "San Andrés",
    "Providencia",
    "Tayrona",
    "Palomino",
    "Minca",
    "Guatapé",
    "Pereira",
    "Manizales",
    "Armenia",
    "Coffee Triangle",
    "Salento",
    "Filandia",
    "Villa de Leyva",
    "Barichara",
    "San Gil",
    "Bucaramanga",
    "Popayán",
    "Pasto",
    "Ipiales",
    "Las Lajas",
    "Cali",
    "Buenaventura",
    "Nuquí",
    "Bahía Solano",
    "Leticia",
    "Amazon",
    "Villavicencio",
    "Caño Cristales",
    "Tunja",
    "Zipaquirá",
    "Salt Cathedral",
    "Monguí",
    "Ráquira",
    "Sogamoso",
  ],
  PE: [
    "Lima",
    "Cusco",
    "Machu Picchu",
    "Arequipa",
    "Puno",
    "Lake Titicaca",
    "Iquitos",
    "Amazon",
    "Trujillo",
    "Chiclayo",
    "Piura",
    "Mancora",
    "Huacachina",
    "Ica",
    "Nazca",
    "Paracas",
    "Ballestas Islands",
    "Huaraz",
    "Cordillera Blanca",
    "Chachapoyas",
    "Kuelap",
    "Gocta Falls",
    "Ayacucho",
    "Huancayo",
    "Tarma",
    "Oxapampa",
    "Tarapoto",
    "Chachapoyas",
    "Cajamarca",
    "Chiclayo",
    "Tumbes",
    "Zorritos",
    "Puno",
    "Uros Islands",
    "Taquile",
    "Amantani",
    "Colca Canyon",
    "Chivay",
    "Yanahuara",
    "Ollantaytambo",
  ],
};
