-- Packing lists generated by AI for each trip (one list per trip)
create table public.packing_lists (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null unique references public.trips (id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index packing_lists_trip_id_idx on public.packing_lists (trip_id);

create or replace function public.set_packing_lists_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger packing_lists_set_updated_at
  before update on public.packing_lists
  for each row
  execute function public.set_packing_lists_updated_at();

alter table public.packing_lists enable row level security;

create policy "Users can select packing lists for their own trips"
  on public.packing_lists
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.trips
      where trips.id = packing_lists.trip_id
        and trips.user_id = auth.uid()
    )
  );

create policy "Users can insert packing lists for their own trips"
  on public.packing_lists
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.trips
      where trips.id = packing_lists.trip_id
        and trips.user_id = auth.uid()
    )
  );

create policy "Users can update packing lists for their own trips"
  on public.packing_lists
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.trips
      where trips.id = packing_lists.trip_id
        and trips.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.trips
      where trips.id = packing_lists.trip_id
        and trips.user_id = auth.uid()
    )
  );

create policy "Users can delete packing lists for their own trips"
  on public.packing_lists
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.trips
      where trips.id = packing_lists.trip_id
        and trips.user_id = auth.uid()
    )
  );
